### ISSUE TITLE
Trinary: Too Trivial?

### ISSUE THREAD

**Issue by Dog** [exercism/xphp#38]
I was looking at Trinary and the problem seems to be trivialized by the `base_convert` and `intval` functions.

I remembered in leap it was explicitly stated that you should not just use the standard library method.

`If your language provides a method in the standard library that does this look-up, pretend it doesn't exist and implement it yourself.`

How should we handle this problem? Should the README for Trinary be updated with the same requirement?

**Comment by kytrinyx** [comment]
Yeah, the point of trinary is to understand the underlying algorithm (same with binary, octal, and hexidecimal). I only added trinary, octal, and hexadecimal because the people I was mentoring didn't seem to "get it" after doing binary. I think perhaps we've deprecated octal, because it's just a tad too much.

**Comment by kytrinyx** [comment]
Updated in d1e0cfa240230684b5007d343e21db4921f793a0
